### ISSUE TITLE
Add screenshot of application

### ISSUE THREAD

**Issue by delanou** [delanou/Reddit-State-Selector#6]
Here is an easy task for Hacktoberfest, can someone figure out how to add screen casts of this application?

**Comment by schalkneethling** [comment]
@delanou What are steps needed to get the app up and running? Is there a running version somewhere one can use? Is it perhaps a web extension?

Also, you title states "screenshot" but, in your description you ask for a "screen cast"? Do you basically want a short "video" of the app in action?

/tag @TremaineNeethling

**Comment by delanou** [comment]
@TremaineNeethling Sorry about that, this project is a browser extension. It does not require any additional installations (used CDNs). A short GIF would be best.

**Comment by schalkneethling** [comment]
Thanks @delanou ~ @TremaineNeethling will get back to you as soon as possible.

**Comment by ghost** [comment]
@delanou What is the name of the extension?

**Comment by delanou** [comment]
@TremaineNeethling Reddit-State-Selector
It is not yet on the extension marketplace if that is what you are wondering.

**Comment by TremaineNeethling** [comment]
Could you send me the crx file for the chrome extension?

**Comment by TremaineNeethling** [comment]
@delanou Could you send me the crx file for the chrome extension?

**Comment by Priyansh2** [comment]
@delanou how to run this extension ,  Can you elaborate on this ? . Is it fine if I will give you the screenshots of this ?

**Comment by ghost** [comment]
@delanou ![reddit-state-selector-extension-test](https://user-images.githubusercontent.com/23447760/31384684-3d207f6c-adc0-11e7-8cbd-9dea567a7d2e.gif)

**Comment by ghost** [comment]
@delanou If you're happy with the GIF, then i'll open a pull request to add it to your repository. is this okay?

**Comment by Priyansh2** [comment]
@delanou it looks like @TremaineNeethling has already solved your problem . So i'm leaving this issue .

**Comment by delanou** [comment]
@TremaineNeethling Where did the background image go and why do the buttons have a different styling?

**Comment by ghost** [comment]
@delanou i cloned the repository and built it with gulp, manually installed it as an extension in chrome and that's the way the extension looked and behaved. to make things easier could you just build and package the extension and send me the packaged extension?
